server:
  port: 9002
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/user/**

            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/product/**,/api/category/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/order/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret:
    key: cMvhfWbh5R+PVQNy2Vda8pSYIxqWEdn1d1M5a/tjACIf6ZCjae9nwK76ONsnTupESdWZtqICdJflKjqan2PlmF5uejGTQdE7qZDVzTFovgIPUG2scweomsf2AbrQM528ODYiZYc2QpD5XZ7jHEHFuiyxvrwnfTJYDR6VbHNSUpM=