server:
  port: 9002
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/user/**

            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/product/**,/api/category/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/order/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret:
    key: NkrN883XSrya6lg6DS+QQAM/kjJMKhxUDcRzr/CaOmtu804Z0qe/cV4KbYiyrQJltYJpA6bL/kPtq+C3/B1yJA==