server:
  port: 9000
spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: kishor@2233#
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
mail:
  hostname: smtp-relay.brevo.com
  port: 587
  username: 9487cf001@smtp-brevo.com
  password: 8IhPqrEZsjA927wz
user:
  email: kishorpandey981@gmail.com
backend_url: http://localhost:9000/api/user
kafka:
  topic:
    name: order-event
app:
  security:
    jwt:
      access-token-expiration: 1200000  #20 min
      refresh-token-expiration: 172800000   #2 days
  disposable-email: 10minutemail,20minutemail,33mail,5ymail,anonbox,guerrillamail,mailinator,maildrop,mailnesia,moakt,my10minutemail,throwawaymail,trashmail,temp-mail,tempmail,truemail,yopmail
jwt:
  secret:
    key: NkrN883XSrya6lg6DS+QQAM/kjJMKhxUDcRzr/CaOmtu804Z0qe/cV4KbYiyrQJltYJpA6bL/kPtq+C3/B1yJA==